#!/usr/bin/python3
# coding: utf-8
"""

 Jade   - Just Another Desktop Environment
 Author - Copyright (c) 2017 Vitor Lopes
 url    - https://github.com/codesardine/Jadesktop

"""
import os
from functools import lru_cache as cache

from gi.repository import Gtk, WebKit2, Gio
from j.AK import Api, AppWindow, settings
from lib import menu, icons, utils

Api.html = Api.Fs.open_file(
    os.path.dirname(os.path.realpath(__file__)) + '/theme/jade.html'
).format(
terminal_icon           = icons.get("terminal"),
file_manager_icon       = icons.get("folder"),
browser_icon            = icons.get("browser"),
software_installer_icon = icons.get("system-software-install"),
settings_icon           = icons.get("preferences-desktop"),
user_icon               = icons.get("system-users"),
exit_icon               = icons.get("application-exit"),
logout_icon             = icons.get("system-log-out"),
shutdown_icon           = icons.get("system-shutdown"),
reboot_icon             = icons.get("system-reboot"),
hibernate_icon          = icons.get("system-hibernate"),
suspend_icon            = icons.get("system-suspend"),
sleep_icon              = icons.get("system-hibernate"),
search_icon             = icons.get("search"),
about_jade_icon         = icons.get("dialog-information"),
distro_logo             = icons.get(settings("app", "distribution_logo")),
user_name               = utils.get_user_name()
)


class JadeWindow(AppWindow):
    """
    extends AK.AppWindow functionality
    """

    OTHER_NAVIGATION_MAP = {
        "open-browser:": 'xdg-open http:',
        "open-file-manager:": 'xdg-open $HOME',
        "open-software-installer:": '$JADE_SOFTWARE_INSTALLER',
        "open-terminal:": '$JADE_TERMINAL',
        "log-out:": 'loginctl terminate-session $XDG_SESSION_ID',
        "power-off:": 'systemctl poweroff',
        "reboot:": 'systemctl reboot',
        "hibernate:": 'systemctl hibernate',
        "suspend:": 'systemctl suspend',
        "sleep:": 'systemctl hybrid-sleep',
    }

    def __init__(self):

        super(JadeWindow, self).__init__()

        @cache(maxsize=None)
        def on_decide_policy(webview, decision, decision_type):

            """

            :param webview:
            :param decision:
            :param decision_type:
            :return: if is not a predicted action do nothing.
            """
            def deny():
                decision.ignore()
                return True

            def execute(command):

                """

                :param command: shell command to execute.
                :return: we are not loading a url don't follow link or we get a blank page.
                """
                utils.run(command)
                deny()

            if decision_type == WebKit2.PolicyDecisionType.NAVIGATION_ACTION:

                navigation_action = decision.get_navigation_action()
                navigation_request = navigation_action.get_request()
                navigation_type = navigation_action.get_navigation_type()
                url = navigation_request.get_uri()

                if url.startswith("file://") and url.endswith("/jade/"):
                    pass

                elif url.startswith("open:"):
                    command = url.replace('open:', 'xdg-open ')
                    execute(command)

                elif url.startswith("desktop:"):
                    url = url.replace('desktop:', '')
                    get_desktop_file = Gio.DesktopAppInfo.new_from_filename(url)
                    command          = get_desktop_file.get_executable()
                    name             = get_desktop_file.get_display_name()
                    print(f"Launching - {name}")
                    print(f" Command - {command}")
                    execute(command)

                elif navigation_type == WebKit2.NavigationType.LINK_CLICKED:
                    print("Link Clicked")
                    print(f"{url} <- Action Denied Repeated URL")
                    deny()

                elif navigation_type == WebKit2.NavigationType.OTHER:
                    print("Other Request " + url)
                    command = JadeWindow.OTHER_NAVIGATION_MAP.get(url, None)
                    if command is not None:
                        execute(command)
                    else:
                        deny()
                else:
                    deny()

            return False

        def on_title_changed(webview, title):

            """

            :param webview:
            :param title:
            """
            title_name = webview.get_title()

            if title_name.startswith("disk-usage"):
                percentage = utils.get_disk_usage()
                self.webview.run_javascript(f'$(".disk-percentage").text("{percentage}");getDiskColors();')

        self.webview.connect("notify::title", on_title_changed)
        self.webview.connect("decide-policy", on_decide_policy)


utils.get_user_style()
menu.Get()
JadeWindow()
utils.autostart()
Gtk.main()
